version: "3.8"
services:
    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=synthea
        - POSTGRES_USER=${POSTGRES_USER}
      ports:
        - 5432:5432
    load_to_omop:
      build: load_to_omop
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=synthea
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - SYNTHEA_VERSION=${SYNTHEA_VERSION}
      volumes:
        - ./output:/output
        - ${VOCAB_PATH}:/vocabulary
